//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAuction
    {
        public int IdProductAction { get; set; }
        public double Price { get; set; }
        public System.DateTime Date { get; set; }
        public int AuctionIdAuction { get; set; }
        public int UserIdUser { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
    }
}
