//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMapper.EFDataMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public Auction()
        {
            this.ProductActions = new HashSet<ProductAction>();
        }
    
        public int IdAuction { get; set; }
        public byte BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal StartPrice { get; set; }
        public bool Finished { get; set; }
        public int UserIdUser { get; set; }
        public int CurrencyIdCurrency { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<ProductAction> ProductActions { get; set; }
    }
}
